/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Poseidon, PoseidonInterface } from "../../ZKHunt.sol/Poseidon";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[3]",
        name: "inputs",
        type: "uint256[3]",
      },
    ],
    name: "poseidon",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Poseidon__factory {
  static readonly abi = _abi;
  static createInterface(): PoseidonInterface {
    return new utils.Interface(_abi) as PoseidonInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Poseidon {
    return new Contract(address, _abi, signerOrProvider) as Poseidon;
  }
}
