/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "JungleEnterVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.JungleEnterVerifier__factory>;
    getContractFactory(
      name: "JungleMoveVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.JungleMoveVerifier__factory>;
    getContractFactory(
      name: "Poseidon",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Poseidon__factory>;
    getContractFactory(
      name: "ZKHunt",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZKHunt__factory>;

    getContractAt(
      name: "JungleEnterVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.JungleEnterVerifier>;
    getContractAt(
      name: "JungleMoveVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.JungleMoveVerifier>;
    getContractAt(
      name: "Poseidon",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Poseidon>;
    getContractAt(
      name: "ZKHunt",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZKHunt>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
